include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gen.dart'
    - '**/generated_plugin_registrant.dart'
    - 'lib/firebase/**.dart'
linter:
  rules:
    public_member_api_docs: false
