name: synapse
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  animated_text_kit: ^4.2.2
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.3
  flutter_lucide: ^1.2.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  path_provider: ^2.1.3
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  shadcn_ui: ^0.6.1
  simple_result: ^1.1.0

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.3.3
  riverpod_lint:
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fixture/
    - assets/json/
