name: synapse
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '^3.3.0'

dependencies:
  animated_text_kit: ^4.2.2
  background_downloader: ^8.5.2
  collection: ^1.18.0
  equatable: ^2.0.5
  file_picker: ^8.0.6
  fllama:
    git:
      url: https://github.com/Telosnex/fllama.git
      ref: main
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.3
  flutter_lucide: ^1.3.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  shadcn_ui: ^0.6.4
  shimmer: ^3.0.0
  simple_result: ^1.1.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
dev_dependencies:
  build_runner:
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.3.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fixture/
    - assets/json/
    - assets/image/
    - assets/logo/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

icons_launcher:
  image_path: 'assets/logo/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  image: assets/logo/logo.png
  color: '#ffffff'
  image_dark: assets/logo/logo-dark.png
  color_dark: '#121212'

  android_12:
    image: assets/logo/logo.png
    icon_background_color: '#ffffff'
    image_dark: assets/logo/logo-dark.png
    icon_background_color_dark: '#121212'
